### ISSUE TITLE
setting time/timezone

### ISSUE THREAD

**Issue by Harshilmalhotra** [huishun98/recurring-messages-telebot#7]
![image](https://user-images.githubusercontent.com/111488708/185323428-1945a248-adab-4dc3-af29-dd2dd97bde8b.png)
Respected sir I am facing below issue with your @cron_telebot telegram bot
Actually when it asks for timezone  i enter +5:30 . But bot replies "you know thats not right".
Kindly resolve this issue

**Comment by huishun98** [comment]
Previously the bot requires the UTC specification to follow this regex strictly: `^(([+-])(2[0-3]|[01][0-9]):([0-5][0-9]))$`, so the timezone you'd need to specify is `+05:30` instead of `+5:30`.

This specification is relaxed in a recent commit, users should not face this issue anymore: https://github.com/hsdevelops/rm-bot/commit/2af386e5b0a12232554dde80fe44f8abf2fa211e
